### ISSUE TITLE
Any way to update the databases?

### ISSUE THREAD

**Issue by ctschach** [scipag/vulscan#11]
Is there any way to update the databases to the latest version. Data here seems to be from 2013 which is kind of outdated.

**Comment by AlekKras** [comment]
In closed issues you can find issue #6 here (https://github.com/scipag/vulscan/issues/6). It should help you

**Comment by touati-coessi** [comment]
I suggested to write a script updating the local atabases only if the remote ones have been updated since last sync.

**Comment by blackout314** [comment]
http://www.computec.ch/mruef/software/nmap_nse_vulscan/cve.csv dead link

**Comment by marcruef** [comment]
Just fixed the links.
