### ISSUE TITLE
Vulscan.nse variable 'strsplit' not declared

### ISSUE THREAD

**Issue by jeg139** [scipag/vulscan#20]
hi guy thanks for your work that's good project,

I have this issues when running nmap --script=vulscan/vulscan.nse -pxx-xxxx -xxx.xxx.xxx.xxx
i have error Vulscan.nse variable 'strsplit' not declared in line 331
nmap is 7.80 version and fresh install of vulscan and db work well with other script.
maybe need some change? or i'm doing wrong something..

**Comment by SolomonSklash** [comment]
I am getting the same issue:
```
NSE: vulscan against 192.168.xxx.xxx:21 threw an error!
/usr/bin/../share/nmap/scripts/vulscan/vulscan.nse:331: variable 'strsplit' is not declared
stack traceback:
        [C]: in function 'error'
        /usr/bin/../share/nmap/nselib/strict.lua:80: in metamethod '__index'
        /usr/bin/../share/nmap/scripts/vulscan/vulscan.nse:331: in global 'find_vulnerabilities'
        /usr/bin/../share/nmap/scripts/vulscan/vulscan.nse:294: in function </usr/bin/../share/nmap/scripts/vulscan/vulscan.nse:224>
        (...tail calls...)
```
```
Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.3 openssl-1.1.1c libssh2-1.8.0 libz-1.2.11 libpcre-8.39 libpcap-1.9.0 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```
Running on Debian Sid.

**Comment by zhankehua** [comment]
Replace "stdnse. strsplit" with "stringaux. strsplit" in the vulscan. nse file and it will work properly.
before use stringaux,you must require it.  local stringaux = require("stringaux")

**Comment by jeg139** [comment]
Thanks it worked.
I close the issue.

**Comment by NothinRandom** [comment]
Is there a way to get the current running version of nmap (i.e. if 7.6 then use stdnse, else use stringaux)?  I tried to use try/catch and switch between the two, but it still threw same error.  The only thing left that I could think of now is to add argument to specify version of nmap and switch based on result
