### ISSUE TITLE
another error line 224 (...tail calls...)

### ISSUE THREAD

**Issue by jeg139** [scipag/vulscan#22]
stack traceback:
	[C]: in function 'error'
	/usr/bin/../share/nmap/nselib/strict.lua:80: in metamethod '__index'
	/usr/bin/../share/nmap/scripts/vulscan/vulscan.nse:474: in global 'extract_from_table'
	/usr/bin/../share/nmap/scripts/vulscan/vulscan.nse:340: in global 'find_vulnerabilities'
	/usr/bin/../share/nmap/scripts/vulscan/vulscan.nse:294: in function </usr/bin/../share/nmap/scripts/vulscan/vulscan.nse:224>
	(...tail calls...)

**Comment by marcruef** [comment]
Please run Nmap with the argument `-d` and paste your output in the reply. Perhaps the issue got also fixed with commit https://github.com/scipag/vulscan/commit/50a1480f670288d80bd668c6264ff06891f08a98 already.

**Comment by jeg139** [comment]
I didn't have time to test already, i'll test as soon as i can and report if it is fixed.

**Comment by jeg139** [comment]
It's good, no error when running the last version. Thanks.
