### ISSUE TITLE
release tags

### ISSUE THREAD

**Issue by anthraxx** [scipag/vulscan#24]
Hi, I would like to ask if it is possible to create git tags when updating databases or such. This would make it more convenient to use latest intended versions as distro package version.
If not, i could try to look into packaging pinned snapshot versions once in a while, but if its not much hassle for you to tag if people in a distro should pull in the changes, that would be awesome :cat:

**Comment by anthraxx** [comment]
@marcruef gentle ping :smile_cat:

**Comment by marcruef** [comment]
Sorry for the late response! Somehow I didn't get a proper notification.

Sure, we can do that. Do you have a suggestion how to do it?

**Comment by anthraxx** [comment]
i don't quite mind, maybe just tag and increase the minor version whenever some portion of database adjustments happened. For now this could be labeled `2.1`
```
git tag 2.1
git push --tags origin
```
Bonus points if you want to commit into always signing your release tags for additional security, but this is a long term commitment because unsigned releases will then be seen as potentially malicious :smile_cat: 
```
git tag --sign 2.1
git verify-tag 2.1
git push --tags origin
```

Thank you very much, I really appreciate that and will update the distro package as soon as releases will be tagged in git :cat:

**Comment by anthraxx** [comment]
@marcruef any time to look into this?

**Comment by marcruef** [comment]
Yes, we will do that. Haven't had the chance to make an update lately.

**Comment by anthraxx** [comment]
Hey, what happened to the release? Just see a silent close of this issue :(

**Comment by marcruef** [comment]
Hello,

We are preparing the release right now.

Bye, Marc

**Comment by anthraxx** [comment]
@marcruef thats awesome :heart: 
But i'm a bit confused, I'm seeing a 2.0 release on github now but the old homepage already had a 2.0 release done in 2014 or such https://www.computec.ch/projekte/vulscan/?s=download

**Comment by marcruef** [comment]
Indeed, this was a typo. Just fixed it. Sorry for the confusion.

**Comment by anthraxx** [comment]
super awesome, thanks a lot :partying_face:
