### ISSUE TITLE
[enhancement]

### ISSUE THREAD

**Issue by sophisticcitizen** [scipag/vulscan#25]
adding [spyse](spyse.com) to nmap could increase the speed. But for some tasks you probably will need nmap.

**Comment by marcruef** [comment]
Thank you for the suggestion. This looks interesting.

At the moment we do not support external API calls as they might be very time consuming, not easy to prevent unwanted exhaustion, and may considered by some as breach of privacy.

But we are thinking to add this optional feature in the future.
