### ISSUE TITLE
Custom database with more than one tag.

### ISSUE THREAD

**Issue by Davetheraveuk** [scipag/vulscan#26]
I have a custom database that I would like to use in my vulnerability scans
Its name is **allcves.csv** and the fields are:

`CVEID,Severity,Description,Published,Added,Modified,Solution,Related,Url`

The fields are self-explanatory as to what they mean.
I have had a darn good go at modifying your vulscan.nse script but after 3 days I am stumped.
I would like the output to look the following:

`CVEID | Severity | Description | Solution`

Can you please help or advise?
If so, then thanks.

**Comment by marcruef** [comment]
Unfortunately mapping a custom amount of new fields is not possible at the moment.

You might be adding just one custom field but putting multiple information in that field with a custom syntax (e.g. newline).
