### ISSUE TITLE
Provide option to hide uber-verbose output if service version is unknown

### ISSUE THREAD

**Issue by chris-aeviator** [scipag/vulscan#29]
When scanning with vulscan, oftentimes nmap is not able to determine a servers/services version it is running. This might be a security measure etc. .

An exemplary output is

```
PORT     STATE SERVICE VERSION
80/tcp   open  http    Apache httpd
|_http-server-header: Apache
```

What this results in is vulscan seemingly printing every known vulnerability for the service, which can easily create a 15.000 lines file. While having a file with every known vulnerability is fine this makes it very hard to navigate the file if the unknown version happens on a low port nr (e.g. Apache 80) and consequently all other ports are somewhere below.

I propose to introduce either a result limiting option (`--result-limit-per-port=5000`) or a general --skip-if-version-unknown that would skip searching for results if the version is unknown.

An alternative to this approach would be to write to a separate file if a certain threshold is crossed, e.g. `out_port_80` when the file was originally created as `out`   

EDIT:

I did not check beforehand if the nmap scripting system allows for additional command line flags

**Comment by Stefan-mcp** [comment]
agreed - i find this makes the tool unusable

**Comment by marcruef** [comment]
Thank you for the suggestion.

We might add a feature which prevents the script from collecting too many items in the future. Unfortunately this is the case when nmap provides very generic product information.
