### ISSUE TITLE
Customized output

### ISSUE THREAD

**Issue by charles-d-burton** [scipag/vulscan#30]
I'm trying to get the output to be fully formed xml and it doesn't seem to be working.  I'm firing with this option
```bash
--script-args-file=/go/bin/args.txt
```
and the contents of the file are
```bash
vulscanoutput='<id>{id}</id><product>{product}</product><version>{version}</version>'
```

But the output isn't modified.  It just comes out as the standard output that it uses by default.

**Comment by marcruef** [comment]
Unfortunately the DB files are hardcoded. Take a look at the line "Add your own database" to find the array with the CSV files. You have to change or add your own file name in it.
