### ISSUE TITLE
Update Databases

### ISSUE THREAD

**Issue by danzee1** [scipag/vulscan#32]
Hi @0x6d69636b 

I think while running script, it should automatically download the latest *.nse databases and then move ahead for the scanning process. At least after 1 day or 2 days... It should do this process whenever use try to scan something. 

Thanks.

**Comment by marcruef** [comment]
Hello,

Thank you for your suggestion.

Indeed, we are thinking about adding an auto update feature in the future. We have noted your vote on our internal roadmap.

Having the script doing this always and without being manually triggered by the user might not be the right solution as some see it as breach of privacy.

Bye, Marc

**Comment by JeffreyShran** [comment]
> Having the script doing this always and without being manually triggered by the user might not be the right solution as some see it as breach of privacy.

Why not just add the option to send a flag via --script-args. So by default it doesn't update but if a flag is set by the user it checks for updates. Maybe it should be the other way around, always update and if people aren't happy they can set the flag to turn it off?
