### ISSUE TITLE
vulscan.nse scans an IP address for more than 1 day

### ISSUE THREAD

**Issue by trietptm** [scipag/vulscan#5]
I have a case where vulscan.nse scans an device's IP address for more than 1 day. Is there any debugging information I could provide to you?

**Comment by marcruef** [comment]
Sure, just add the parameter _-d2_ or even _-d3_ and post the output.

**Comment by trietptm** [comment]
Today I retest and I could not reproduce the bug. I will test with your parameters when I see the bug again :) .
